### ISSUE TITLE
#TK06 Diseño Lógico que consta de la Normalización y el Modelo Relacional

### ISSUE THREAD

**Issue by FacKuSalvatierra** [FacKuSalvatierra/CBA-FLY#10]

**Comment by eliasgiannantonio** [comment]
![drawSQL-cba-fly-export-2023-05-03](https://user-images.githubusercontent.com/105678923/236334736-674ce94c-740a-403b-808a-826c632b1c5a.png)

### Re-diseño completo de la base de datos:

- **Usuarios**: Esta tabla debe almacenar la información de los usuarios registrados, como su nombre completo, correo electrónico, contraseña, etc.
- **Vuelos**: Esta tabla debe almacenar la información básica de cada vuelo, como el origen, el destino, la hora de salida, la hora de llegada, la duración del vuelo, el número de vuelo, el tipo de avión, etc.
- **Asientos**: Esta tabla debe almacenar la información sobre los asientos disponibles en cada vuelo, como el número de asiento, la clase del asiento (económica, ejecutiva, etc.), el precio del asiento, si está disponible o no, etc.
- **Carrito de compras**: Esta tabla debe almacenar la información sobre los vuelos que los usuarios han agregado a su carrito de compras, como el ID del usuario, el ID del vuelo, la cantidad de asientos que se han agregado, etc.
- **Compras**: Esta tabla debe almacenar la información sobre las compras realizadas por los usuarios, como el ID del usuario, el ID del vuelo, la cantidad de asientos comprados, el precio total de la compra, etc.
- **Pagos**: Aquí se almacena la información de los pagos de los usuarios registrados, numero de tarjeta, fecha de expiración, etc.
