### ISSUE TITLE
#TK11 - subir documentacion faltante

### ISSUE THREAD

**Issue by FacKuSalvatierra** [FacKuSalvatierra/CBA-FLY#15]
Subir documento con los integrantes actualizados

**Comment by Lucas-Balduzzi** [comment]
Actualizado - "CBA FLY - IEEE-830". Formulario en carpeta "Documentacion" con nueva lista de integrantes.
Actualizado - "README.md". Cambio de lista de integrantes: "Cancinos" por "Balduzzi".

Enviado - "Planilla de Propuesta de Proyecto.docx" con Integrantes actuales a "Evidencia 2: Sprint 0".
Enviado - "Registro de grupos - Proyecto Integrador" con los integrantes actuales al formulario ".docx".
https://docs.google.com/forms/d/e/1FAIpQLSdorzS4A3mqkWRRpZRP1vc0UNhYt8LMwIQVyCkFMFsSpj6kDQ/viewform

Solicitud de Modificación - "Registro de grupos Proyecto Final Modulo Programador Web (respuestas)" para actualizar integrantes cambiando datos de integrante "Cancinos" por "Balduzzi" de archivo ".xlsx".
https://docs.google.com/spreadsheets/d/1l5jRzUoQpSr-egJcjtzN3zfOIgxUz2RoROeNsEOOn2M/edit#gid=82005427

**Comment by Lucas-Balduzzi** [comment]
Registro de grupos realizado exitosamente, corroborado por Profesora Viviana Guillen.
