### ISSUE TITLE
#TK13: Swiper/Slider funciona solo al cargar el sitio.

### ISSUE THREAD

**Issue by eliasgiannantonio** [FacKuSalvatierra/CBA-FLY#27]
El Swiper/Slider no funciona de una manera esperada. 
Al cambiar de sección o vista el swiper deja de funcionar, solo arranca al inicializar el sitio o recargando la página.

**Comment by Amadeo-G** [comment]
Solucionado el bug del swiper/slider. Ahora funciona correctamente al cambiar de secciones, inicializándose sin ningún problema.
