### ISSUE TITLE
#TK21 : Establecer el modelo de base de datos del primer sprint en Django usando clases.

### ISSUE THREAD

**Issue by FacKuSalvatierra** [FacKuSalvatierra/CBA-FLY#37]

**Comment by eliasgiannantonio** [comment]
Creación de clases en models.py hecha (CBA-FLY\backend\api\models.py)
![ray-so-export](https://github.com/FacKuSalvatierra/CBA-FLY/assets/105678923/96252693-c8e6-4936-b155-29fcebca6773)
