### ISSUE TITLE
#TK25 : implementacion de clases del Models.py

### ISSUE THREAD

**Issue by FacKuSalvatierra** [FacKuSalvatierra/CBA-FLY#41]
- Vuelo. (FacKu)
- asiento.(FacKu)
- Pago.(Elias)
- Compra.(Romi)
- CarritoCompra.(Lucas B.)

**Comment by eliasgiannantonio** [comment]
Se implementa la clase de "Pagos"

![image](https://github.com/FacKuSalvatierra/CBA-FLY/assets/105678923/99ee7a6a-4e17-4417-94ea-50dd4cbf0953)

Recordemos que para que este objeto funcione y reciba los datos, primero nuestro usuario/cliente debe registrarse e iniciar sesión en su cuenta. Cuando el usuario ya haya iniciado sesión, haya reservado su asiento y cargue su información de pago, se crea una instancia del modelo Pagos en la base de datos para registrar los detalles del mismo.

**Comment by FacKuSalvatierra** [comment]
Se implemento la clase de "Vuelo"

![Vuelo](https://github.com/FacKuSalvatierra/CBA-FLY/assets/98361543/a1a61a0b-b06d-4535-8c68-7968a3048d1a)

**Comment by FacKuSalvatierra** [comment]
Se agrego la clase "Asiento"

![asiento](https://github.com/FacKuSalvatierra/CBA-FLY/assets/98361543/501f9085-f0ff-4e98-8d0b-8bc04afe26e7)

**Comment by Lucas-Balduzzi** [comment]
Implementacion de CarritoCompras

![django](https://github.com/FacKuSalvatierra/CBA-FLY/assets/106196812/ee1f4f39-3c27-47b9-aa70-e8e7ce9e5f99)
