### ISSUE TITLE
#TK24: Revisión y corrección de models.py (Agregar clases meta a cada tabla)

### ISSUE THREAD

**Issue by eliasgiannantonio** [FacKuSalvatierra/CBA-FLY#42]
Se pretende agregar las clases Meta descriptivas correspondientes a cada objeto.
Ejemplo:
![image](https://github.com/FacKuSalvatierra/CBA-FLY/assets/105678923/05c2cab3-35d4-425c-98c3-adb4621ef314)

**Comment by candelaiaraneil** [comment]
clases Meta agregadas
