### ISSUE TITLE
#TK05 Diseño Físico que es el script legible de la DB en MySQL.

### ISSUE THREAD

**Issue by FacKuSalvatierra** [FacKuSalvatierra/CBA-FLY#9]

**Comment by eliasgiannantonio** [comment]
### Script de SQL re-diseñado y actualizado
El nuevo script y el nuevo diagrama ER fue re-diseñado y actualizado acorde a los requisitos del proyecto. En cuanto a los principales cambios del nuevo diseño:

- Se eliminan las tablas de filtros min y max (Ya que implementaremos esta opción utilizando una cláusula WHERE en la consulta SQL y una interfaz de usuario en la aplicación web.)
- Se elimina la tabla de "Ticket"; tenemos planeado implementar tickets electrónicos a través de JavaScript o PHP.
- Mediante la normalización eliminamos la redundancia de tablas, teniendo así un diseño mas compacto y efectivo.
